name: "Metablock Ingress Action"
description: "Update the ingress configuration for a block"
inputs:
  token:
    description: "Metablock API token - can be set as METABLOCK_API_TOKEN env variable"
  space:
    description: "Metablock Space - can be set as METABLOCK_SPACE env variable"
  path:
    description: "Path to yaml files of blocks - can be set as METABLOCK_PATH env variable"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - metablock
    - apply
    - ${{ inputs.path }}
    - "--token"
    - ${{ inputs.token }}
    - "--space"
    - ${{ inputs.space }}
