name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - run: make image

  test:
    runs-on: ubuntu-latest
    env:
      METABLOCK_API_TOKEN: ${{ secrets.METABLOCK_API_TOKEN }}
      METABLOCK_SPACE: mblock

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: apply ingress
        uses: ./
        with:
          path: example
