name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      METABLOCK_API_TOKEN: ${{ secrets.METABLOCK_API_TOKEN }}
      METABLOCK_SPACE: mblock

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: apply ingress
        uses: ./
        with:
          path: example
